### PR TITLE
Fix second batch of comments

### PR DESCRIPTION
**Pull request by CohenArthur**
No worries little squirrel, here is some text to make you happy. This is in reference to our review from the Rust-for-linux/linux fork

### CODE REVIEW

**Comment by ksquirrel** [comment]
Review of `f97fd89966de`:
  - ⚠️ The PR body message looks too short.
  - ❌ Commit [`5fc3766`](https://github.com/ks0n/linux/commit/5fc376606fc08e52f683e9ec21b8cc8d16603ba5): The commit message needs to be at least 3 lines long: title, empty line, signature.
  - ❌ Commit [`f97fd89`](https://github.com/ks0n/linux/commit/f97fd89966de3311f9bd7b26bf88be869bc3ce5a): The commit message needs to be at least 3 lines long: title, empty line, signature.

**Comment by ksquirrel** [comment]
Review of `35926053d855`:
  - ⚠️ The PR body message looks too short.
  - ✔️ Commit [`c250e4b`](https://github.com/ks0n/linux/commit/c250e4b10dcc43a92b66741e42185cec51fcae4f): Looks fine!
  - ✔️ Commit [`3592605`](https://github.com/ks0n/linux/commit/35926053d8553e1293f913c29a453dc53c1e45bc): Looks fine!

**Review by Skallwar — APPROVED** [review]
When @n1tram1 will have review, I will change the author as usual and push the commit on the other branch to avoid ksquirrel flood on the PR to Rust-for-Linux

**Review by n1tram1 — APPROVED** [review]

**Comment by ksquirrel** [comment]
Review of `41ac95971113`:
  - ⚠️ Commit [`41ac959`](https://github.com/ks0n/linux/commit/41ac95971113fa6db83967bb8d28975a17803589): The commit committer does not match the commit author.
  - ❌ Commit [`41ac959`](https://github.com/ks0n/linux/commit/41ac95971113fa6db83967bb8d28975a17803589): The last line of the commit message must be a `Signed-off-by` and must match the submitter of the PR.

**Comment by ksquirrel** [comment]
Review of `792b82e7cdf6`:
  - ✔️ Commit [`792b82e`](https://github.com/ks0n/linux/commit/792b82e7cdf6a0e3fec955e38502b4bfc7eedb6e): Looks fine!

**Pull request merged**
